### ISSUE TITLE
Cannot use Image Mosaic Wall on Windows

### ISSUE THREAD

**Issue by cgilles** [scheckmedia/ImageMosaicWall#10]
See the full described report from digiKam bugzilla :

 https://bugs.kde.org/show_bug.cgi?id=424605

NOTE: It's not only for Windows, the problem can be reproduced under Linux too

BEst

Gilles Caulier

**Comment by scheckmedia** [comment]
I've done some changes in branch v0.2. It would be nice if you can check whether the error still occurs.

**Comment by cgilles** [comment]
Thanks i will checkout code and test

**Comment by cgilles** [comment]
Tested here. Problem is fixed now with code from branch v0.2

**Comment by cgilles** [comment]
[fix_resource_init.patch.txt](https://github.com/scheckmedia/ImageMosaicWall/files/5028112/fix_resource_init.patch.txt)

A small patch against v0?2 branch to fix resource init in the plugin and fix some typos

Best

Gilles Caulier

**Comment by scheckmedia** [comment]
I recently released v0.2. Further bugs should be addressed in a new issue

**Comment by cgilles** [comment]
Thanks Tobias.
