### ISSUE TITLE
Can load base image but doesn't find images in folder

### ISSUE THREAD

**Issue by sguyader** [scheckmedia/ImageMosaicWall#11]
Both in the standalone app and in the digikam plugin, I can set the base image just fine but when I set image folder (which contains regular jpeg's) it doesn't seem to find any image (it shows `Images in Folder: 0`) and the "Create Mosaic" button stays greyed out (by the way there's a typo, it shows "Create **Mosqiac**").

**Comment by scheckmedia** [comment]
Currently the folder will be not scanned recursively.

**Comment by sguyader** [comment]
OK. I saw the video and that you used drag and drop of the image folder, it works that way.
You can close the issue if you want, though I think the button should work as I used it.
Thanks

**Comment by scheckmedia** [comment]
No it's definitely a bug or at least a feature request. Recursively folder scan is a must have :)

**Comment by scheckmedia** [comment]
should be solved with the freshly released version v.0.2
