### ISSUE TITLE
GUI not correctly showing on Small Screen - Unable to Resize the window (top/bottom) and Maximize

### ISSUE THREAD

**Issue by manikandancode** [scheckmedia/ImageMosaicWall#13]
Tested on Ubuntu and Lubuntu with 1366x768  screen resolution.
Installation via portable AppImage : ImageMosaicWall-x86_64.AppImage

Please check the images
![bug](https://user-images.githubusercontent.com/46480489/94058155-4f2b9c00-fdfe-11ea-99fc-27d2ace4b32e.png)
![bug2](https://user-images.githubusercontent.com/46480489/94058166-50f55f80-fdfe-11ea-8ecd-338b7c269ba1.png)

**Comment by scheckmedia** [comment]
I've added a fix for this issue. It would be nice if you can give it a try by building the app by yourself.

**Comment by manikandancode** [comment]
If possible release as portable AppImage

**Comment by scheckmedia** [comment]
[ImageMosaicWall-x86_64.zip](https://github.com/scheckmedia/ImageMosaicWall/files/5432578/ImageMosaicWall-x86_64.zip)

**Comment by manikandancode** [comment]
Thanks a lot. Now working. Release this.
