### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [scheckmedia/ImageMosaicWall#2]
Please provide the AppImage file for download on GitHub Releases. Thanks.

Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by scheckmedia** [comment]
Thanks for the advice!

**Comment by probonopd** [comment]
Thanks. Added to the [AppImageHub](https://appimage.github.io/apps/) central directory of available AppImages.
