### ISSUE TITLE
It crashes when it has to deal with over 100 images

### ISSUE THREAD

**Issue by tiotrom** [scheckmedia/ImageMosaicWall#3]
If I select a folder with 100+ images it simply crashes. I am using the appimage on Linux. Thanks for the app! ;)

**Comment by scheckmedia** [comment]
Hello @tiotrom, can you please tell me what kind of Linux distribution you use and in which version? I'll have a look at what causes the error.

**Comment by tiotrom** [comment]
I use Manjaro Stable with the latest updates. Gnome 3.36 and kernel 5.4

**Comment by scheckmedia** [comment]
I've done some changes in branch v0.2. It would be nice if you can check whether the error still occurs.

**Comment by scheckmedia** [comment]
I recently released v0.2, this bug should be fixed.

**Comment by tiotrom** [comment]
Thank you very much!
